In [206]:
#Importing packages and data

import pandas as pd
import numpy as np
from sklearn import linear_model, metrics, preprocessing
from scipy.stats import norm
from numpy import mean
from numpy import std
import random
import pandas as pd
import numpy as np

iris = pd.read_csv('iris.csv', delimiter=',', header = None)
iris.head(5)

     0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [207]:
def find_distribution(data):
    u = mean(data)
    sg = std(data)
    normal_dist = norm(u, sg)
    return normal_dist

In [208]:
def probability(X, dist1, dist2, dist3, dist4):
    return dist1.pdf(X[0]) * dist2.pdf(X[1]) * dist3.pdf(X[2]) * dist4.pdf(X[3])

In [209]:
def separate_by_class(dataset):
    separated = dict()
    for index, row in dataset.iterrows():
        class_value = row[4]
        if class_value not in separated:
            separated[class_value] = list()
        separated[class_value].append(row)
    return separated
separated_dataset = separate_by_class(train)

In [210]:
def predictedClass(data, prob_setosa, prob_versicolor, prob_virginica):
    max_prob = [0] * len(data)
    predicted = [""] * len(data)
    for i in range(len(data)):
        max_prob[i] = max(prob_setosa, prob_versicolor, prob_virginica)
        if max_prob[i] == prob_setosa:
            predicted[i] = "Iris-setosa"
        elif max_prob[i] == prob_versicolor:
            predicted[i] = "Iris-versicolor"
        else:
            predicted[i] = "Iris-virginica"
    return predicted

In [211]:
#splitting train test

train = iris.sample(frac=0.8)
test = iris.drop(train.index)
train.reset_index()
test.reset_index()

test.head()

      0    1    2    3            4
2   4.7  3.2  1.3  0.2  Iris-setosa
9   4.9  3.1  1.5  0.1  Iris-setosa
15  5.7  4.4  1.5  0.4  Iris-setosa
20  5.4  3.4  1.7  0.2  Iris-setosa
21  5.1  3.7  1.5  0.4  Iris-setosa

In [212]:
#separating the data classwise
separated = separate_by_class(train)
X_seto = separated['Iris-setosa']
X_versi = separated['Iris-versicolor']
X_virgi = separated['Iris-virginica']
X_seto = pd.DataFrame(X_seto)
X_versi = pd.DataFrame(X_versi)
X_virgi = pd.DataFrame(X_virgi)

In [213]:
# pdf of each class for each attribute
# print(X_seto)
X1_seto = find_distribution(X_seto[0])
# print(X1_seto)
X2_seto = find_distribution(X_seto[1])
X3_seto = find_distribution(X_seto[2])
X4_seto = find_distribution(X_seto[3])

X1_versi = find_distribution(X_versi[0])
X2_versi = find_distribution(X_versi[1])
X3_versi = find_distribution(X_versi[2])
X4_versi = find_distribution(X_versi[3])

X1_virgi = find_distribution(X_virgi[0])
X2_virgi = find_distribution(X_virgi[1])
X3_virgi = find_distribution(X_virgi[2])
X4_virgi = find_distribution(X_virgi[3])


diff = [] # array to hold diff between model output and actual class on test data


for index, row in test.iterrows():
    X_test = [row[0], row[1], row[2], row[3]]
    Y_test = row[4]
    prob_seto = probability(X_test, X1_seto, X2_seto, X3_seto, X4_seto)
    prob_versi = probability(X_test, X1_versi, X2_versi, X3_versi, X4_versi)
    prob_virgi = probability(X_test, X1_virgi, X2_virgi, X3_virgi, X4_virgi)
    predicted = predictedClass(X_test, prob_seto, prob_versi, prob_virgi)
    Y_pred = max (predicted, key=predicted.count)

# if diff[i] == 0, means output and actual class has no diff    
    if str(Y_pred) == str(Y_test):
#         print("diff: ", 0)
        diff.append(0)
    else:
#         print("diff: ", 1)
        diff.append(1)

# print(diff)


wrong = sum(diff)
accurate = len(diff) - wrong
print("accuracy: ", accurate/len(diff)*100)

accuracy:  100.0